### ISSUE TITLE
Credentials via environment variables 

### ISSUE THREAD

**Issue by enniomara** [JonasAlfredsson/gateway_jumper#2]
As a way to add more flexibility to the script, the credentials (jump pass, totp secret & dest_pass) could be loaded through [environment variables](https://stackoverflow.com/questions/38623378/expect-script-environment-variable-issue). 

This opens the possibility of using other storage backends such as [1password cli](https://1password.com/downloads/command-line/) and [bitwarden](https://bitwarden.com/help/article/cli/).

**Comment by JonasAlfredsson** [comment]
Interesting.
Sou you suggest something like this in the beginning?

```
set local_pass $env(GWJ_LOCAL_PASS)
set jump_pass $env(GWJ_JUMP_PASS)
set totp_secret $env(GWJ_TOTP_SECRET)
set dest_pass $env(GWJ_DEST_PASS)
```

**Comment by enniomara** [comment]
Exactly!

**Comment by JonasAlfredsson** [comment]
Alright, I will take a look at this tomorrow, since it will require a bit of editing in the README :)

**Comment by JonasAlfredsson** [comment]
Alright, test this and see what you think :)

**Comment by enniomara** [comment]
Looking good, thank you!

**Comment by JonasAlfredsson** [comment]
Excellent! Closing this now then :)
